version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: ${PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - backend
    ports:
      - "5432:5432"
  symfony:
    build: ./docker/image/symfony
    container_name: ${PROJECT_NAME}-symfony
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - XDEBUG_MODE=coverage
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - backend
  nginx:
    build: ./docker/image/nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - .:/app
    ports:
      - 8080:80
    networks:
      - default
      - backend
    depends_on:
      - symfony
    environment:
      - NGINX_BACKEND_DOMAIN=${PROJECT_NAME}
networks:
  backend:
  default:
volumes:
  database_data:
